version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: QRAXTm109!
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-QRAXTm109!}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

#  cleanup:
#    container_name: cleanup_container
#    image: postgres  # Use the same base image as your other services
#    volumes:
#      - postgres:/data/postgres
#      - pgadmin:/var/lib/pgadmin
#    command: ["sh", "-c", "docker-compose down -v"]
#
## Define networks, volumes, etc. here...

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
